### ISSUE TITLE
Download

### ISSUE THREAD

**Issue by TeaqariaWTF** [DismissedGuy/1Password-Android-BrowserCompat#1]
I wonder where I can download u module,, Thanks for your work

**Comment by malmeloo** [comment]
Hey! Looks like the workflow isn't working correctly so there are no downloads for now. If you clone/download the repository, you can build it yourself by executing the `gradlew.bat` script (or `./gradlew` on linux/mac). Either that or wait a bit, I'll fix it asap.

**Comment by TeaqariaWTF** [comment]
I don't have a computer right now, I have no choice but to wait.

I wonder if Mull browser and Iceraven browser will be supported

**Comment by TeaqariaWTF** [comment]
With Termux I think I managed to create it, but I don't know where it registered the module

![Screenshot_20230906-234549_Termux](https://github.com/DismissedGuy/1Password-Android-BrowserCompat/assets/90970076/78a0cfec-c69d-4c03-aefb-a4b170d3ad0c)

**Comment by malmeloo** [comment]
I've just updated the workflow which I think fixes the issue, so if you have a few minutes I should have an APK for you.

Are you willing to test mull/iceraven for me? I will add them to the module's list, if they work I can include them in a release.

**Comment by malmeloo** [comment]
It's already done, here you go: https://github.com/DismissedGuy/1Password-Android-BrowserCompat/suites/15895982340/artifacts/907231210

**Comment by TeaqariaWTF** [comment]
I can confirm that it works on Mull browser and Iceraven

**Comment by malmeloo** [comment]
Are you sure? I'm yet to add those package IDs...

**Comment by TeaqariaWTF** [comment]
Mull and iceraven are based on Fennec I think that's why they work smoothly

**Comment by malmeloo** [comment]
The module looks at the package IDs and only force-enables if they match from its built-in list. Currently only fennec is on that list (org.mozilla.fennec_fdroid), but mull or iceraven aren't, so it should fallback to default 1Password behavior.

**Comment by TeaqariaWTF** [comment]
https://github.com/DismissedGuy/1Password-Android-BrowserCompat/assets/90970076/5beba491-ee84-4030-a235-698dfd4fd5b1

**Comment by TeaqariaWTF** [comment]
https://github.com/DismissedGuy/1Password-Android-BrowserCompat/assets/90970076/278a7a41-51b3-4112-93da-1eaa4cdd3dd5

**Comment by malmeloo** [comment]
Okay, I have no clue why that works haha. Let's continue in #2; can you test that apk and let me know if it works? I'm going to close this as there is a proper release now.

(I'll most likely see your reply tomorrow in ~20 hrs, it's late + work)

**Comment by TeaqariaWTF** [comment]
Everything seems to be working for me right now.
I can only ask for one feature.
Lsposed should also specify which application to select.

I'm attaching an image here and these are automatically selected

![Screenshot_20230907-003044_Kabuk](https://github.com/DismissedGuy/1Password-Android-BrowserCompat/assets/90970076/02dbc881-f8b0-4c79-9c25-656cd6ea4bbe)
